### ISSUE TITLE
Staker contract

### ISSUE THREAD

**Issue by pedrohba1** [equals9-com/eq9-token-contracts#1]
No contrato de staker, temos alguns requisitos:

- Precisamos de alguma maneira de saber onchain todo mundo que está fazendo stake em um endereço específico
- Precisamos de alguma maneira onchain de saber todos os stakes, quanto, e qual a timestamp, para calcular o valor por período de tempo no back-end
- O stake funcion apenas com EQ9
- O unstake pode ser realizado a qualquer momento. Se o unstake for de 100% do valor, a timestamp deve ser voltar para um valor indefinido (0?). Isso porque o tempo é relevante, e um usuário sem tempo de stake não pode ganhar recompensas por tempo.
- Após um unstake ser realizado, é preciso colocar o saldo em uma variável que irá armazená-lo. Esse saldo intermediário não conta como stake. O usuário só poderá retirar esse saldo após 24 horas.

Para o contrato inteligente de Staker:
Precisaremos onchain apenas das lista de stakes feitos em uma wallet. Isso é suficiente para fazer a disribuição. O resto pode ser descoberto por meio de eventos. Por exemplo, se queremos saber quantos stakes a minha carteira deu, podemos usar o The Graph para fazer a indexação dos eventos do contrato e armazenar a informação de "quantos stakes a minha carteira tem" numa estrutura graphQL. 

Se tivermos onchain a lista de stakes sendo feitos em cima de um endereço, temos que ter um jeito de fazer uma busca rápida num array. Existe uma implementação de busca O(log n) em `@openzeppelin/contracts/utils/Arrays.sol`

A outra opção, é armazenar o índice nos eventos, e no momento de stake e unstake, usar esse índice para ter acesso O(1). O difícil é garantir que não há usuários repetidos no array. Para isso, podemos usar esse contrato da Open Zeppelin: https://docs.openzeppelin.com/contracts/3.x/api/utils#EnumerableSet

**Comment by pedrohba1** [comment]
Pergunta pertinente: 

Qualquer unstake a gente reseta o tempo de stake do user?
Por exemplo, se ele faz um unstake de 1 EQ9 e ele tem 10 mil em stake num user.
A gente deveria resetar a tiestamp do cara? Pra ele ganhar menos no tempo.

**Comment by LeandroFontellas** [comment]
> Pergunta pertinente:
> 
> Qualquer unstake a gente reseta o tempo de stake do user? Por exemplo, se ele faz um unstake de 1 EQ9 e ele tem 10 mil em stake num user. A gente deveria resetar a tiestamp do cara? Pra ele ganhar menos no tempo.

Acredito que sim, atualmente a função de claim() só permite que o usuário dê claim após 24 horas da ultima vez que ele fez unstake(), evitando que o usuário faça multiplos unstakes. Porém uma pergunta que ficou no ar, o que acontece se o usuário der unstake() e não der claim(), os tokens deveriam retornar a serem staked nos players? Ou os tokens em questão vão ficar lá para sempre para serem claimed.

```solidity
function unstake(uint256 _amount, address _player) public {
        require(
            stakerAddresses[_player].contains(msg.sender),
            "You are not staking into this player address"
        );
        require(
            _amount <= stakerAmounts[_player][msg.sender],
            "Not enough staked amount into the player"
        );

        if (stakerAmounts[_player][msg.sender] == _amount) {
            stakerAddresses[_player].remove(msg.sender);
            stakerTimestamps[_player][msg.sender] = 0;
        }

        lastTimeUserUnstake[msg.sender] = block.timestamp;
        stakerAmounts[_player][msg.sender] -= _amount;
        claimAmount[msg.sender] += _amount;
        emit Unstaked(_amount, _player, msg.sender);
 }
    
function claim() external {
        require(
            block.timestamp >= lastTimeUserUnstake[msg.sender] + 24 hours,
            "Unable to claim, 24 hours still have not have passed"
        );

        eq9Contract.transfer(msg.sender, claimAmount[msg.sender]);
        claimAmount[msg.sender] = 0;
 }
```

**Comment by pedrohba1** [comment]
> Porém uma pergunta que ficou no ar, o que acontece se o usuário der unstake() e não der claim(), os tokens deveriam retornar a serem staked nos players? Ou os tokens em questão vão ficar lá para sempre para serem claimed.

Sim, eles ficam lá para serem claimed().
A ideia é a mesma do contrato de paymentSplitter:
Como fazer a transferência custa gás, a gente deixa pro usuário fazer. Caso contrário, seria inviável fazer todos os claim() por causa do custo.

**Comment by pedrohba1** [comment]
Agora, pra finalizar, acho que só falta fazer uma função que reverte o stake e o claim para a carteira do staker.
Isso porque é possível que seja preciso fazer uma atualização nesse contrato. Então precisamos de um jeito de reverter todos os stakes, por meio de uma função que só pode ser chamada pelo Onwer do contrato

**Comment by pedrohba1** [comment]
Fizemos todos os requisitos. Vou fechar a issue.
